version: '3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: legaltech
      POSTGRES_USER: legaltech
      POSTGRES_PASSWORD: Aryaarya123@
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: legaltech
      POSTGRES_USER: legaltech
      POSTGRES_PASSWORD: Aryaarya123@

volumes:
  db:
  nextcloud:
